### PR TITLE
Shark 0.9 fix Hive JDBC on JDK7 and add an ant target to build a debian package

### PR DESCRIPTION
**Pull request by mbautin**
Two fixes (Hive trunk patches still under review but hopefully we can get this into the shark-0.9 branch sooner): fix annoying JDK7 Hive JDBC build problems, and add a target to build a Debian package (we need that to deploy the Shark-customized version of Hive). The goal is to get all these patches into the official Hive trunk and 0.9 branch as well, of course.

### CODE REVIEW

**Comment by rxin** [comment]
Thanks. Do you know what the status is for the Apache Hive trunk merge? I saw on the JIRA tickets that there were some minor changes.

Does it matter of we merge this into 0.9 while Hive doesn't?

**Comment by mbautin** [comment]
Hive should definitely merge these in. I will ping the dev mailing list.

**Comment by mbautin** [comment]
Reynold: I've sent a message to the hive dev mailing list and cc'd you. Also I think it would be fine to commit these changes to amplab/hive for now to make it easier for people to build/test shark. We can always switch to the official Hive branch once all required patches go in.

**Comment by mbautin** [comment]
Now that things have started moving forward with getting these patches into Hive, I think it is OK to hold off on this pull request until we get patches into official Hive trunk/0.9.

**Comment by mbautin** [comment]
Closing this pull request. I will open another one with a more complete list of patches.

**Pull request closed without merging**
